### PR TITLE
Clean up event loop left overs from promise

### PR DESCRIPTION
**Pull request by WyriHaximus**
I somehow missed those while working on https://github.com/php-http/react-adapter/pull/50

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

### CODE REVIEW

**Comment by dbu** [comment]
neat, no more passing the event loop around :+1: 

can you run the cs fixer, or apply the reported changes by hand please?

**Comment by dbu** [comment]
and once this is merged, should i tag 4.0.0 with it?

**Comment by WyriHaximus** [comment]
> can you run the cs fixer, or apply the reported changes by hand please?

Sure let me fix those.

> neat, no more passing the event loop around 👍
> and once this is merged, should i tag 4.0.0 with it?

There is one more thing to consider. And that is that the event loop isn't needed anymore in this pack even for the HTTP client. The same Loop::get() is used internally there when no event loop is provided. And since async and await also do that it can be removed there as well. (Already prepaeed a branch for that if you want to do that.)

**Comment by WyriHaximus** [comment]
Opened the client changes in draft over at https://github.com/php-http/react-adapter/pull/58 It would require this one to be merged first.

**Pull request merged**
