### PR TITLE
allow the whole range of react stream pre-releases

### PR DESCRIPTION
**Pull request by dbu**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | follow-up #28
| Documentation   | -
| License         | MIT

#### What's in this PR?

Allow all versions of react/stream between 0.4.3 and 0.8 instead of only 0.4 and 0.8 versions.

#### Why?

Semver for 0.x releases only includes a minor version when using `^`.

### CODE REVIEW

**Comment by dbu** [comment]
@samuelnogueira i wanted to release a new version after merging #28 and checked the diff again, and noticed that version constraint on react/stream. does it make sense as i specify it here?

**Comment by samuelnogueira** [comment]
Actually, is it possible to remove the constraint on react/stream altogether, given that it isn't directly used by this library?

**Comment by dbu** [comment]
actually.... lets see if travis-ci agrees that we can drop this.

**Comment by dbu** [comment]
@shulard travis-ci thinks this is ok. do you agree?

**Comment by shulard** [comment]
Hello,

I think it's ok the react/stream dependency was used before relying on StreamFactory. If this part is required by react elsewhere it will be defined as a dependency on the corresponding lib.

**Comment by dbu** [comment]
thanks.

**Pull request merged**
